import Navbar from './components/Navbar'
import './globals.css'
import { Pixelify_Sans } from 'next/font/google'

const pixel = Pixelify_Sans({ subsets: ['latin'], weight:['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pixel.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
